apiVersion: extensions/v1beta1
kind: Deployment
metadata:
	name: myweb
spec:
	replicas: 3
	template:
		metadata:
		labels:
		app: httpd
	spec:
		containers:
		-	name: front-end
			image: httpd
			ports:
- containerPort: 80